hero_image: /assets/hero-platform.jpeg
about_image: /assets/offshore-facility.jpeg
welding_image: /assets/welding.jpeg
mission_image: /assets/offshore-facility.jpeg
vision_image: /assets/welding.jpeg
values_image: /assets/pipes.jpeg
service_image: /assets/pipelines.jpeg
cashes_image: /assets/platform-tall.jpeg
